import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Satisfy } from 'next/font/google'

import './globals.css'
import Navbar from './_components/Navbar'
import Footer from './_components/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const satisfy = Satisfy({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Prime Table App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
        <Navbar />
        <main className="px-[77px] mt-[100px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
