export const headers = [
  'ID',
  'Customer',
  'Date',
  'Table',
  'Party Size',
  'Status',
]

export const tableData = [
  {
    id: 1,
    customer: 'John Doe',
    date: '2025-09-01',
    table: 'Table 1',
    partySize: 2,
    status: 'Confirmed',
  },
  {
    id: 2,
    customer: 'Jane Smith',
    date: '2025-09-02',
    table: 'Table 4',
    partySize: 4,
    status: 'Pending',
  },
  {
    id: 3,
    customer: 'Michael Lee',
    date: '2025-09-02',
    table: 'Table 2',
    partySize: 3,
    status: 'Cancelled',
  },
  {
    id: 4,
    customer: 'Sophia Brown',
    date: '2025-09-03',
    table: 'Table 6',
    partySize: 5,
    status: 'Confirmed',
  },
  {
    id: 5,
    customer: 'David Wilson',
    date: '2025-09-04',
    table: 'Table 3',
    partySize: 2,
    status: 'Pending',
  },
  {
    id: 6,
    customer: 'Emily Johnson',
    date: '2025-09-05',
    table: 'Table 7',
    partySize: 6,
    status: 'Confirmed',
  },
  {
    id: 7,
    customer: 'Daniel Martinez',
    date: '2025-09-06',
    table: 'Table 2',
    partySize: 4,
    status: 'Cancelled',
  },
  {
    id: 8,
    customer: 'Olivia Garcia',
    date: '2025-09-07',
    table: 'Table 8',
    partySize: 3,
    status: 'Confirmed',
  },
  {
    id: 9,
    customer: 'James Anderson',
    date: '2025-09-08',
    table: 'Table 5',
    partySize: 2,
    status: 'Pending',
  },
  {
    id: 10,
    customer: 'Mia Rodriguez',
    date: '2025-09-09',
    table: 'Table 1',
    partySize: 4,
    status: 'Confirmed',
  },
  {
    id: 11,
    customer: 'William Clark',
    date: '2025-09-10',
    table: 'Table 6',
    partySize: 3,
    status: 'Pending',
  },
  {
    id: 12,
    customer: 'Isabella Lewis',
    date: '2025-09-11',
    table: 'Table 3',
    partySize: 5,
    status: 'Confirmed',
  },
  {
    id: 13,
    customer: 'Ethan Walker',
    date: '2025-09-12',
    table: 'Table 7',
    partySize: 2,
    status: 'Cancelled',
  },
  {
    id: 14,
    customer: 'Charlotte Hall',
    date: '2025-09-13',
    table: 'Table 4',
    partySize: 6,
    status: 'Confirmed',
  },
  {
    id: 15,
    customer: 'Benjamin Young',
    date: '2025-09-14',
    table: 'Table 2',
    partySize: 3,
    status: 'Pending',
  },
  {
    id: 16,
    customer: 'Amelia King',
    date: '2025-09-15',
    table: 'Table 8',
    partySize: 4,
    status: 'Confirmed',
  },
  {
    id: 17,
    customer: 'Lucas Wright',
    date: '2025-09-16',
    table: 'Table 5',
    partySize: 2,
    status: 'Pending',
  },
  {
    id: 18,
    customer: 'Harper Scott',
    date: '2025-09-17',
    table: 'Table 1',
    partySize: 5,
    status: 'Confirmed',
  },
  {
    id: 19,
    customer: 'Henry Adams',
    date: '2025-09-18',
    table: 'Table 6',
    partySize: 3,
    status: 'Cancelled',
  },
  {
    id: 20,
    customer: 'Evelyn Baker',
    date: '2025-09-19',
    table: 'Table 7',
    partySize: 4,
    status: 'Confirmed',
  },
  {
    id: 21,
    customer: 'Alexander Perez',
    date: '2025-09-20',
    table: 'Table 3',
    partySize: 2,
    status: 'Pending',
  },
  {
    id: 22,
    customer: 'Scarlett Rivera',
    date: '2025-09-21',
    table: 'Table 5',
    partySize: 6,
    status: 'Confirmed',
  },
  {
    id: 23,
    customer: 'Mason Torres',
    date: '2025-09-22',
    table: 'Table 1',
    partySize: 3,
    status: 'Cancelled',
  },
  {
    id: 24,
    customer: 'Avery Ramirez',
    date: '2025-09-23',
    table: 'Table 8',
    partySize: 4,
    status: 'Pending',
  },
  {
    id: 25,
    customer: 'Jack Murphy',
    date: '2025-09-24',
    table: 'Table 2',
    partySize: 5,
    status: 'Confirmed',
  },
  {
    id: 26,
    customer: 'Ella Cooper',
    date: '2025-09-25',
    table: 'Table 6',
    partySize: 2,
    status: 'Cancelled',
  },
  {
    id: 27,
    customer: 'Sebastian Bailey',
    date: '2025-09-26',
    table: 'Table 4',
    partySize: 3,
    status: 'Confirmed',
  },
  {
    id: 28,
    customer: 'Luna Foster',
    date: '2025-09-27',
    table: 'Table 7',
    partySize: 6,
    status: 'Pending',
  },
  {
    id: 29,
    customer: 'Matthew Gray',
    date: '2025-09-28',
    table: 'Table 3',
    partySize: 4,
    status: 'Confirmed',
  },
  {
    id: 30,
    customer: 'Chloe Hughes',
    date: '2025-09-29',
    table: 'Table 5',
    partySize: 2,
    status: 'Cancelled',
  },
]
